excluded:
  - Pods
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation

disabled_rules:
  - unused_closure_parameter
  - object_literal
  - number_separator
  
line_length: 300
number_separator:
  minimum_length: 5

function_parameter_count:
  warning: 5
  error: 10
  
file_length:
   warning: 800
   error: 1200

function_body_length:
  warning: 70
  error: 100

identifier_name:
  min_length: 1
  max_length: 
    warning: 40
    error: 45

custom_rules:
  discouraged_image_literal:
    name: "Discouraged Image Literal"
    regex: "#imageLiteral"
    message: "Please use UIImage(named:) instead"
    severity: warning

